# Generated by Django 3.2.6 on 2021-08-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_is_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='article.IpAddress', verbose_name='بازدید ها'),
        ),
    ]
