# Generated by Django 3.2.6 on 2021-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profiles', verbose_name='عکس'),
        ),
    ]
