# Generated by Django 3.2.6 on 2021-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_author',
            field=models.TextField(default='سلام', max_length=200, verbose_name='درباره نویسنده'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='آدرس اکانت فیسبوک'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='آدرس اکانت اینستاگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='آدرس اکانت توییتر'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='آدرس اکانت یوتیوب'),
        ),
    ]
