# Generated by Django 3.2.6 on 2021-09-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210907_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube_id',
        ),
    ]
